### PR TITLE
ADEHJKNTV 1337 edited words in readme.

### PR DESCRIPTION
**Pull request by lvn**
#### What's this PR do?

Changes a bunch of words in the readme.
#### Where should the reviewer start?

Everywhere
#### How should this be manually tested?

Fuck you
#### Any background context you want to provide?

No.
#### What are the relevant tickets?

ADEHJKNTV 1337
#### What gif best describes this PR or how it makes you feel?

asdfsdfasdf
#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [ ] Does this PR require a blog post? If so, ensure marketing has signed off on content.
- [ ] Does the [knowledge base](https://sprint.ly/docs) need to be updated?
- [ ] Does this add new dependencies? If so, does Chef, M4, or PIP requirements need to be updated?
- [ ] Will this feature require a new piece of infrastructure be implemented?
- [ ] Are any new services fully automated in Chef?
- [ ] Are there ChefSpec tests for the new Chef recipes/cookbooks?
- [ ] Does this PR require new Mixpanel or GA events?
- [ ] Is there appropriate logging included?

fuck off

### CODE REVIEW

**Comment by lvn** [comment]
@Uberi review pls SDJKFHADFJJDFHASDFJSDFASDFKLSDJFKL;AJSDFL JASLKDJFAKL;SDFJLKASDFJL AJSDLFSAJDL ASFJ,AJLSD ;AFASJ LSADFJ ASDFJD LADF

**Comment by Uberi** [comment]
pls

**Comment by Uberi** [comment]
needs more databinding

**Comment by dhop** [comment]
+1

**Pull request merged**
