### PR TITLE
ADEHJKNTV 1338 added a bunch of stuff pls

### PR DESCRIPTION
**Pull request by lvn**
#### What's this PR do?

`ADDS THINGS`
#### Where should the reviewer start?

`index.js`
#### How should this be manually tested?

You can't. Yung.js is a philosophy.

That philosophy is not testing.
#### Definition of Done:
- [ ] Is there appropriate test coverage? (e.g. ChefSpec, Mocha/Chai, Python, etc.)
- [ ] Does this PR require a Selenium test? (e.g. Browser-specific bugs or complicated UI bugs)
- [ ] Does this PR require a regression test? All fixes require a regression test.
- [ ] Does this PR require a blog post? If so, ensure marketing has signed off on content.
- [ ] Does the [knowledge base](https://sprint.ly/docs) need to be updated?
- [ ] Does this add new dependencies? If so, does Chef, M4, or PIP requirements need to be updated?
- [ ] Will this feature require a new piece of infrastructure be implemented?
- [ ] Are any new services fully automated in Chef?
- [ ] Are there ChefSpec tests for the new Chef recipes/cookbooks?
- [ ] Does this PR require new Mixpanel or GA events?
- [ ] Is there appropriate logging included?

### CODE REVIEW

**Comment by lvn** [comment]
@Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi @Uberi

**Comment by lvn** [comment]
pls respond ;_;

**Comment by lvn** [comment]
im so lonely ;_;

**Comment by lvn** [comment]
its so dark in here ;_;

**Comment by Uberi** [comment]
needs

**Comment by Uberi** [comment]
more

**Comment by Uberi** [comment]
databinding

**Pull request merged**
